version: '1.0'
services:
  eventservice:       
    image: eventservice
    environment:
    - "MongoParameters__Address=mongodb://mongodb:27017"
    container_name: eventservice
    depends_on:        
    - mongodb        
    ports:
    - 5010:80        
    restart: always    
  mongodb:
    image: mongo:latest
    ports:
    - 27018:27017              
    restart: always